### ISSUE TITLE
Not translated submenu

### ISSUE THREAD

**Issue by apriljunge** [seebruecke-org/frontend#101]
Lokalgruppe and Sicherer Hafen are not translated
https://www.seebruecke.org/en/join-us/germany/baden-wuerttemberg-1/freiburg-1

![grafik](https://user-images.githubusercontent.com/10660618/214882465-48b63e31-a6e2-4aca-8205-849e9fd8b12e.png)

**Comment by azinazadi** [comment]
This is probably a bug since we migrated to Strapi 4. I will check into it. Sorry I didn't receive the emails from Github. From now on I should get the emails and will react quicker. I am also checking into the Pull Requests. Thanx.

**Comment by 7azin** [comment]
This is probably a bug since we migrated to Strapi 4. I will check into it. Sorry I didn't receive the emails from Github. From now on I should get the emails and will react quicker. I am also checking into the Pull Requests. Thanx.

**Comment by 7azin** [comment]
The menu is showing now. I will fix the translation in the coming days.
https://www.seebruecke.org/mach-mit/deutschland/baden-wuerttemberg/freiburg

**Comment by apriljunge** [comment]
https://github.com/seebruecke-org/frontend/commit/0eb0f9973b1b23a0fed59849168915dc3ae9f503
Is fixed now. Thank you @7azin
