### ISSUE TITLE
Replace or repair embed component

### ISSUE THREAD

**Issue by apriljunge** [seebruecke-org/frontend#105]
The [embed component ](https://github.com/seebruecke-org/frontend/commit/ba4f43fb812c5fc3cfdf50226184e6dbb67d3b97) is an actual security risk (XSS).
It should be completely replaced or (if it's really not possible to do otherwise) at least more security layers have to be added.

At the moment the code is not filtered at all. This should be avoided at all costs, especially in a CMS that is used by multiple actors.
Even if user rights are restricted, the danger of malicious code is reduced, but not eliminated.

Despite of the security risk, you do not have any control about layout, services, etc. This is also an issue with GDPR and cookie law.
Third party scripts and cookies could be loaded without any consent of the user.
Even if you wanted, you could not add a cookie banner, because you can't know what services are used for this component.

As this component is called _Embed_, I am assuming you want to embed things like image galleries, videos or social media posts?
I think there are better solutions. Maybe we can discuss that to find a better and GDPR compatible solution.

**Comment by 7azin** [comment]
This is only there to embed IFrames. I am not GDPR professional, to my simple search it looks [alright to use them](https://iframely.com/docs/gdpr) Do you have more concrete info about it?

I will add filters to make sure this will only be IFrames. Once we have it more in place we will check into which direction it should go. Right now there are wishes to include Youtube Videos and a tool that one SB member developed concerning the Wegweiser action.

We can talk for sure personally about it. I am curious to hear your ideas

**Comment by apriljunge** [comment]
Really interesting article. I have never heard about this opinion :astonished:

I'm not into law at all, but since YouTube has servers in the USA _and_ sets tracking cookies by default, personally I would not agree with this article. When I researched I found [multiple](https://complianz.io/youtube-and-the-gdpr-how-to-embed-youtube-on-your-site/) [articles](https://www.blogmojo.de/youtube-videos-datenschutzkonform-einbetten/) [about](https://cookieplugins.com/en/embedding-gdpr-compliant-youtube-videos/) youtube embedding and gdpr that state:
at least use _www.youtube-nocookie.com_ instead of youtube.com, better: insert an placeholder and load the video on click (2-click solution). As this website acts in a political context I personally think that the Seebrücke website should provide the best data protection possible with a 2-click solution. [It even speeds up loading times](https://buhalbu.com/nextjs/articles/next-js-adventures-embedded-youtube-videos) :sparkles:.

A more straight forward approach than filtering could be to change the embed field to an url field.
It has many more advantages
- more secure
- you can have full control about the iframe properties and display
- you can rewrite urls (youtube.com to youtube-nocookie.com for example) or add parameters
- you can have a allow list for all allowed urls to prevent unwanted services are included

What do you think? Would this meet the requirements? :relaxed:

**Comment by 7azin** [comment]
Yes I like the ideas. I will work towards a solution. I will write here
more concretely. Thanx

Am Samstag, 25. März 2023 schrieb Gregor ***@***.***>:

**Comment by 7azin** [comment]
I will implement OEmbed which needs to be activated first to show the content
