### ISSUE TITLE
Images do not load properly

### ISSUE THREAD

**Issue by apriljunge** [seebruecke-org/frontend#106]
Images usually load very slowly, sometimes not at all.
I don't know if this is related to the configuration of next.js or the problem is server side.

**Comment by 7azin** [comment]
This is more serverside. Sometimes after a fresh deploy it takes some time until the images are cached, they are slow for the first load. There are also more problems with images, e.g. some won't load on Safari. If you find concrete problems with images that I can reproduce, it would help to dig into it...

**Comment by apriljunge** [comment]
I can't find problems with concrete images or a reproducible procedure.

Right now the header image on the start page and the images for the "Mach mit" and "Spenden" teasers do not load for me.
But just larger resoltions. If I resize to a smaller view it totally works. So there's no issue with the image itself, but only with some of the sizes.


As this is a backed issue should I move this to cms repo?

**Comment by 7azin** [comment]
The storage space responsible for cache has been overloaded. I think this was the main reason for the failures. Please write here if the images still have problems, if we don´t see this in the next month I will close this issue.
