### ISSUE TITLE
Logo broken

### ISSUE THREAD

**Issue by apriljunge** [seebruecke-org/frontend#108]
![grafik](https://user-images.githubusercontent.com/10660618/233778022-e766a6c1-774f-4d6b-ad95-903fecee5f2b.png)
The logo in the header is broken

**Comment by apriljunge** [comment]
https://github.com/seebruecke-org/frontend/commit/a8eac824aea3cf5f4889bf631b5a1040411df76e
This commit caused te issue

**Comment by Haliax** [comment]
It is also a problem for the Event-List.

![Screenshot from 2023-04-22 12-51-58](https://user-images.githubusercontent.com/30631206/233779842-6885babc-6808-4835-9cb3-39c8e3389bea.png)
