### ISSUE TITLE
"Null" place on online events

### ISSUE THREAD

**Issue by apriljunge** [seebruecke-org/frontend#118]
https://www.seebruecke.org/aktionen/online-event-local-innovation-in-migration-governance-sharing-best-practices-in-cities
![grafik](https://github.com/seebruecke-org/frontend/assets/10660618/4234f73e-36fd-4bfd-aee0-eeab76e1484e)

On online events null is printed as event location

**Comment by 7azin** [comment]
Vielen Dank, ich werde die Issues in der kommende Woche fixen.
