### ISSUE TITLE
machine-readable access to list of actions

### ISSUE THREAD

**Issue by derhuerst** [seebruecke-org/frontend#93]
Hey! 👋

I maintain [`seebruecke-events-calendar-feed`](https://github.com/derhuerst/seebruecke-events-calendar-feed), a dynamically generated [iCalendar](https://icalendar.org) feed that people can subscribe to in their personal calendar apps, allowing them to notice Seebrücke actions without opening the website.

It seems like the website has been rebuilt, and is now a Next.js app, so the calendar feed currently fails to extract the list of actions.

Is there a way to obtain the list of actions in a machine-readable way, under a stable URL? I could only find `https://seebruecke.org/_next/data/xi2YC3KuSjTC7rxlWTUM3/de/actions.json`, but it seems like this URL contains a build ID or something similar and will therefore break soon.

If there is no such API, can we add it? If you give me a hint on how to approach this, I'll happily submit a PR.

Alternatively, is there a way to obtain a completely static, server-side-rendered version of the page, so that I can continue scraping the actions from the HTML?

**Comment by derhuerst** [comment]
have you had a chance to look at this? 🙂

**Comment by derhuerst** [comment]
How do the `sort` and `where` arguments of the actions()` field work?

Ideally, I want to sort actions by `start` date, descending, and only find actions whose `start` date is `>= (today - 30 days)`.

**Comment by apriljunge** [comment]
I found [a code snippet](https://github.com/seebruecke-org/frontend/blob/38e8c603769d9ee7bc52fa2bcef41db765406bfa/lib/actions.js#L88-L91) in this repo where they filter actions by date. 
I think they're using the strapi [graphql plugin](https://docs.strapi.io/developer-docs/latest/development/plugins/graphql.html). Based on this documentation I built this and it worked.

You can use `start_lt` (lower than) or `start_lte` (lower than equals). I think for your case it makes not difference. Instead of filtering by start you could also use `limit`.

```graphql
query {
  actions (
    sort: "start:asc",
    where: {
      start_lt: "2022-12-18T00:00:00.000Z",
      end_gt: "2022-12-17T00:00:00.000Z",
    }
  )
  {
    id,
    title,
    start,
    end,
    location,
    location_detail,
    slug,
  }
}
```

**Comment by derhuerst** [comment]
Thanks for the hint!

I noticed that the actions currently don't have a `link`, even though the website has a page for each action:

```graphql
{
	action(id: "841") {
		link
	}
}
```

```json
{
	"data": {
		"action": {
			"link": null
		}
	}
}
```

[*Reclaim the Hinterland* action page](https://www.seebruecke.org/aktionen/reclaim-the-hinterland)

Do you know why @Halifax @azinazadi?

**Comment by azinazadi** [comment]
What I can tell from looking into the DB is that the link points to an external link for some actions
![grafik](https://user-images.githubusercontent.com/770005/208289827-c45890bd-1282-46fb-bc78-426d987a2e7a.png)

**Comment by azinazadi** [comment]
To make the url in SB website you could use the slug ( https://www.seebruecke.org/aktionen/{slug} ). Soon will come also the english website, but the german urls wouldn't be affected...

Is there anything I can help still?

**Comment by derhuerst** [comment]
> Is there anything I can help still?

Having the group's and/or city's timezone specifier (e.g. `Europe/Helsinki`) would be great! Currently, I assume `Europe/Berlin` for all actions.

**Comment by derhuerst** [comment]
The following query is currently extremely slow (~60s):

```graphql
query recentActions ($start_gte: String!) {
  actions(
    sort: "start:desc"
    where: {
      start_gte: $start_gte
    }
    limit: 5
    
	) {
    id
    slug
    updated_at
    locale
    title
    start, end
    location, location_detail
    coordinates
    link
    group {
      localizations {
        content {
          ...on ComponentSharedBlocksContact {
            __typename
            email
          }
        }
      }
      city {
        name
        slug
        federal_country {
          slug
          country {
            slug
          }
        }
      }
    }
  }
}
```

```json
{
  "start_gte": "2022-12-12T12:12Z"
}
```

**Comment by apriljunge** [comment]
> Having the group's and/or city's timezone specifier (e.g. Europe/Helsinki) would be great! Currently, I assume Europe/Berlin for all actions.

I completely on your side

**Comment by azinazadi** [comment]
ok great to see it working. about time zone, the time of the actions refer to the local time that it takes place. We also store the coordinations where the event takes place and the city:

![grafik](https://user-images.githubusercontent.com/770005/208307362-9d991dc7-4989-4e3b-9f61-c9963db884ed.png)

maybe they could be used to automatically detect the timzone...

**Comment by apriljunge** [comment]
> Having the group's and/or city's timezone specifier (e.g. Europe/Helsinki) would be great! Currently, I assume Europe/Berlin for all actions.

In this repository the timezone is also fixed to Europe/Berlin. That is definitely not ideal. As long as this is not handled differently in the Seebrücke frontend, I think you should also keep it static to avoid possible deviations.

Maybe we should create a new issue for this?

https://github.com/seebruecke-org/frontend/blob/38e8c603769d9ee7bc52fa2bcef41db765406bfa/lib/actions.js#L15

**Comment by derhuerst** [comment]
I'm closing this, as the access to the API works for me. Thanks.
